# Generated by Django 4.0.5 on 2022-06-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('size_m2', models.FloatField()),
                ('price', models.FloatField()),
                ('price_per_m2', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('url', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
