# Generated by Django 4.0.5 on 2022-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_alter_house_bathrooms_alter_house_bedrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCountByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100)),
                ('property_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
