# Generated by Django 4.0.5 on 2022-06-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_propertycountbytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='property_id',
            new_name='house_id',
        ),
    ]
