# Generated by Django 4.0.5 on 2022-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_soldhouses_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='house_id',
            field=models.CharField(max_length=100),
        ),
    ]
