version: '3.3'

services:
  web:
    build: ./glasshouse
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./glasshouse:/usr/src/app
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - redis

  celery:
    build: ./glasshouse
    command: celery -A glasshouse worker --loglevel=INFO -f celery.log
    volumes:
      - ./glasshouse:/usr/src/app
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:6-bullseye

  celery-beat:
    build: ./glasshouse
    command: celery -A glasshouse beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./glasshouse:/usr/src/app
    env_file: .env
    depends_on:
      - redis
