version: '3.3'

services:
  web:
    build: ./glasshouse
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./glasshouse:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 [::1]
    depends_on:
      - redis

  celery:
    build: ./glasshouse
    command: celery -A glasshouse worker --loglevel=INFO -f celery.log
    volumes:
      - ./glasshouse:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 [::1]
    depends_on:
      - redis

  redis:
    image: redis:6-bullseye

  celery-beat:
    build: ./glasshouse
    command: celery -A glasshouse beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./glasshouse:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 [::1]
    depends_on:
      - redis
