version: '3.3'

services:
  db:
    image: postgres:14-bullseye
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env

  web:
    build: ./glasshouse
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./glasshouse:/usr/src/app
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

  celery:
    build: ./glasshouse
    command: celery -A glasshouse worker --loglevel=INFO -f celery.log
    volumes:
      - ./glasshouse:/usr/src/app
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:6-bullseye

  celery-beat:
    build: ./glasshouse
    command: celery -A glasshouse beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./glasshouse:/usr/src/app
    env_file: .env
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    #    restart: 'no'
    volumes:
      - ./prometheus_data:/etc/prometheus
    ports:
      - 9090:9090
    network_mode: host

  grafana:
    image: grafana/grafana
    restart: 'no'
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    network_mode: host
