# Generated by Django 4.0.5 on 2022-06-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_rename_property_id_house_house_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldHouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('size_m2', models.FloatField()),
                ('price', models.CharField(max_length=100)),
                ('price_per_m2', models.FloatField()),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('rec_date', models.DateField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.house')),
            ],
        ),
    ]
