# Generated by Django 4.0.5 on 2022-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0009_house_city_house_country_house_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='newly_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
