# Generated by Django 4.0.5 on 2022-07-01 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0010_house_newly_listed_house_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldhouses',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soldhouses',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soldhouses',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soldhouses',
            name='newly_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soldhouses',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soldhouses',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soldhouses',
            name='price',
            field=models.FloatField(),
        ),
    ]
