# Generated by Django 4.0.5 on 2022-07-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0011_soldhouses_city_soldhouses_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='pub_date',
            new_name='date_published',
        ),
        migrations.AddField(
            model_name='house',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
