# Generated by Django 4.0.5 on 2022-07-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0012_rename_pub_date_house_date_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='date_updated',
            new_name='date_modified',
        ),
    ]
