# Generated by Django 4.0.5 on 2022-07-02 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0013_rename_date_updated_house_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
