# Generated by Django 4.0.5 on 2022-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0014_alter_house_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='newly_listed',
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(blank=True, default='unlisted', max_length=100),
        ),
    ]
