# Generated by Django 4.0.5 on 2022-07-02 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0015_remove_house_newly_listed_house_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldhouses',
            name='newly_listed',
        ),
        migrations.AddField(
            model_name='soldhouses',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldhouses',
            name='date_sold',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='soldhouses',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='size_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldhouses',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soldhouses',
            name='size_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldhouses',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
