# Generated by Django 4.0.5 on 2022-07-02 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0016_remove_soldhouses_newly_listed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldhouses',
            name='date_sold',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
