# Generated by Django 4.0.5 on 2022-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0017_alter_soldhouses_date_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiwanCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('taipei', 'TAIPEI'), ('yilan', 'YILAN'), ('tainan', 'TAINAN')], default='All Cities', max_length=100)),
            ],
        ),
    ]
