# Generated by Django 4.0.5 on 2022-07-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0018_taiwancity'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiwancity',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiwancity',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
