# Generated by Django 4.0.5 on 2022-07-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0019_taiwancity_district_alter_taiwancity_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taiwancity',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='taiwancity',
            name='district',
        ),
        migrations.AddField(
            model_name='taiwancity',
            name='country',
            field=models.CharField(blank=True, default='Taiwan', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TaiwanDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.taiwancity')),
            ],
        ),
    ]
