# Generated by Django 4.0.5 on 2022-07-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0020_rename_city_taiwancity_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taiwandistrict',
            name='city',
        ),
        migrations.DeleteModel(
            name='TaiwanCity',
        ),
        migrations.DeleteModel(
            name='TaiwanDistrict',
        ),
    ]
