# Generated by Django 4.0.5 on 2022-07-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0021_remove_taiwandistrict_city_delete_taiwancity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
