# Generated by Django 4.0.5 on 2022-07-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('rec_date', models.DateField()),
            ],
        ),
    ]
